#!/usr/bin/python3


from conflicts import get_first_conflict
import logging
from sys import argv


if __name__ == "__main__":
    logging.info("launched as: " + ' '.join(argv))
    result = get_first_conflict(argv[1:])
    if result is None:
        print("no conflicts detected")
        exit(0)
    else:
        print(result[0] + " conflicts with "
              + result[1] + " in file " + result[2])
        exit(1)
